# Generated by Django 5.0.6 on 2024-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active'),
        ),
    ]
